name: .NET CI

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: Build configuration
        required: true
        default: Release
        type: choice
        options:
          - Release
          - Debug
  push:
    branches: [ main ]
    tags: [ 'V*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build, Test and Publish
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: src
    env:
      BUILD_CONFIGURATION: ${{ github.event_name == 'workflow_dispatch' && inputs.configuration || 'Release' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8.x SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\NuGet\v3-cache
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: .NET info
        run: dotnet --info

      - name: Restore
        run: |
          dotnet restore Idasen.SystemTray.Win11/Idasen.SystemTray.Win11.csproj
          dotnet restore Idasen.SystemTray.Win11.Tests/Idasen.SystemTray.Win11.Tests.csproj

      - name: Build (${{ env.BUILD_CONFIGURATION }})
        run: |
          dotnet build Idasen.SystemTray.Win11/Idasen.SystemTray.Win11.csproj --configuration $env:BUILD_CONFIGURATION --no-restore
          dotnet build Idasen.SystemTray.Win11.Tests/Idasen.SystemTray.Win11.Tests.csproj --configuration $env:BUILD_CONFIGURATION --no-restore

      - name: Test (${{ env.BUILD_CONFIGURATION }})
        run: |
          dotnet test Idasen.SystemTray.Win11.Tests/Idasen.SystemTray.Win11.Tests.csproj --configuration $env:BUILD_CONFIGURATION --no-build --verbosity normal

      - name: Publish win-x64 (self-contained single file)
        run: >-
          dotnet publish
          Idasen.SystemTray.Win11/Idasen.SystemTray.Win11.csproj
          --configuration $env:BUILD_CONFIGURATION
          --runtime win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -p:PublishReadyToRun=true

      - id: determine_version
        name: Determine version and paths
        run: |
          $projPath = "Idasen.SystemTray.Win11/Idasen.SystemTray.Win11.csproj"
          [xml]$projXml = Get-Content $projPath
          $version = ($projXml.Project.PropertyGroup | ForEach-Object { $_.Version } | Where-Object { $_ } | Select-Object -First 1)
          if (-not $version) { throw "Version not found in $projPath" }

          $publishDir = "Idasen.SystemTray.Win11/bin/$env:BUILD_CONFIGURATION/net8.0-windows10.0.19041/win-x64/publish"
          $exe = Join-Path $publishDir "Idasen.SystemTray.exe"
          if (-not (Test-Path $exe)) { throw "Executable not found: $exe" }

          $publishDirRel = (Join-Path "src" $publishDir) -replace '\\','/'

          # Only exeRel needs to be inside src for artifact upload to work
          $exeRel = (Join-Path "src" $exe) -replace '\\','/'

          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "exe_path=$exeRel" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "publish_dir=$publishDirRel" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - id: checksums
        name: Generate SHA256 checksum
        run: |
          $publishDir = "Idasen.SystemTray.Win11/bin/$env:BUILD_CONFIGURATION/net8.0-windows10.0.19041/win-x64/publish"
          $exe = Join-Path $publishDir "Idasen.SystemTray.exe"
          if (-not (Test-Path $exe)) { throw "Executable not found: $exe" }

          $version = '${{ steps.determine_version.outputs.version }}'

          $exeHash = Get-FileHash -Algorithm SHA256 -Path $exe
          $exeHashLine = "{0}  {1}" -f $exeHash.Hash, (Split-Path -Leaf $exe)
          $exeShaPath = Join-Path $publishDir ("Idasen.SystemTray-{0}-win-x64.exe.sha256" -f $version)
          Set-Content -Path $exeShaPath -Value $exeHashLine -NoNewline

          $exeShaRel = (Join-Path "src" $exeShaPath) -replace '\\','/'
          "exe_sha=$exeShaRel" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Upload artifact (publish directory)
        uses: actions/upload-artifact@v4
        with:
          name: Idasen.SystemTray.Win11-win-x64-publish-${{ steps.determine_version.outputs.version }}
          if-no-files-found: error
          path: ${{ steps.determine_version.outputs.publish_dir }}/**

      - name: Upload exe checksum
        uses: actions/upload-artifact@v4
        with:
          name: Idasen.SystemTray-${{ steps.determine_version.outputs.version }}-win-x64-exe-sha256
          if-no-files-found: error
          path: ${{ steps.checksums.outputs.exe_sha }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/V')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.determine_version.outputs.exe_path }}
            ${{ steps.checksums.outputs.exe_sha }}
