name: SonarCloud Analysis

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarcloud:
    name: SonarCloud Static Code Analysis
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: src
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Setup .NET 8.x SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\NuGet\v3-cache
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\.sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Install SonarCloud Scanner for .NET
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: .NET info
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore Idasen-Desk.sln

      - name: Begin SonarCloud Analysis
        working-directory: ./src/
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: |
          if ([string]::IsNullOrEmpty($env:SONAR_TOKEN) -or [string]::IsNullOrEmpty($env:SONAR_ORGANIZATION)) {
            Write-Warning "SonarCloud secrets not configured. Skipping analysis."
            Write-Warning "Please configure SONAR_TOKEN and SONAR_ORGANIZATION secrets in repository settings."
            exit 0
          }
          dotnet sonarscanner begin /k:"idasen-desk" /o:"${env:SONAR_ORGANIZATION}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="${env:SONAR_TOKEN}" /s:SonarQube.Analysis.xml

      - name: Build
        run: |
          if ([string]::IsNullOrEmpty($env:SONAR_TOKEN) -or [string]::IsNullOrEmpty($env:SONAR_ORGANIZATION)) {
            Write-Host "Skipping build as SonarCloud analysis was skipped"
            exit 0
          }
          dotnet build Idasen-Desk.sln --configuration Release --no-restore
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

      - name: End SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: |
          if ([string]::IsNullOrEmpty($env:SONAR_TOKEN) -or [string]::IsNullOrEmpty($env:SONAR_ORGANIZATION)) {
            Write-Host "Skipping end analysis as SonarCloud analysis was skipped"
            exit 0
          }
          dotnet sonarscanner end /d:sonar.token="${env:SONAR_TOKEN}"
